In [2]:
import numpy as N

In [3]:
Tabl = N.array([[ 1., 0., 0.],
 [ 0., 1., 2.]])
Tabl

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  2.]])

In [4]:
print(Tabl.shape) #argumenty wymiaróœ
print(Tabl.ndim) #liczba wymiarow
print(Tabl.size) #liczba wszytkich elemntow
print(Tabl.dtype) #typ obiektów
print(Tabl.itemsize) #pojemnosc
print(Tabl.data)
a = N.arange(15).reshape(3, 5)
print(a)
print(a.shape)
b = N.array([6,7,8])
print(type(b))

(2, 3)
2
6
float64
8
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
<class 'numpy.ndarray'>


In [5]:
# a = np.array(1,2,3,4)    # WRONG
a = N.array([1,2,3,4])  # RIGHT


In [6]:
c = N.array( [ [1,2], [3,4] ], dtype=complex )
print(c)

[[ 1.+0.j  2.+0.j]
 [ 3.+0.j  4.+0.j]]


In [7]:
a = N.zeros((3,5))
print(a)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [8]:
a = N.ones((2,3,4), dtype= N.int32)
print(a)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [9]:
a = N.empty((2,3))
print(a)

[[  1.08734045e-071   3.97062373e+246   1.16318408e-028]
 [  7.95967296e-042   6.38301085e-067   1.21540486e-046]]


In [10]:
a = N.arange(10,30,5)
print(a)

[10 15 20 25]


In [11]:
N.linspace(0,2,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [12]:
N.array(([[1,3],[2,3]]),ndmin=3)

array([[[1, 3],
        [2, 3]]])

In [13]:
N.array(N.mat('1 2; 3 4'))

array([[1, 2],
       [3, 4]])

In [14]:
N.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [15]:
x = N.array([[1,2,3],[3,3,3]])
x

array([[1, 2, 3],
       [3, 3, 3]])

In [16]:
x.shape

(2, 3)

In [17]:
x = N.zeros_like(x)
x

array([[0, 0, 0],
       [0, 0, 0]])

In [18]:
a = N.ones((5,),dtype= int)
print(a)
print(a.shape)

[1 1 1 1 1]
(5,)


In [19]:
x= N.arange(6)
x = x.reshape((2,3))
print(x)

[[0 1 2]
 [3 4 5]]


In [20]:
N.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

In [21]:
N.empty_like(x)

array([[    140009730809152,     140009730809152,                   0],
       [                  0,     140007343915008, 7310593858020254331]])

In [22]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
N.arange(3,7,2)

array([3, 5])

In [24]:
N.linspace(3,5,num= 4)

array([ 3.        ,  3.66666667,  4.33333333,  5.        ])

In [25]:
N.linspace(3,5,num= 4, endpoint= False)

array([ 3. ,  3.5,  4. ,  4.5])

In [26]:
N.random.rand(3,2)

array([[ 0.93487852,  0.77093014],
       [ 0.05503029,  0.58692527],
       [ 0.41596142,  0.65345949]])

In [27]:
import matplotlib.pyplot as plt
import numpy as N
A = 8
y = N.zeros(8)
x1 = N.linspace(0, 10, A, endpoint=True)
x2 =  N.linspace(0, 10, A, endpoint=False)
plt.plot(x1, y, 'o')
plt.plot(x2, y + 0.5, 'o')
plt.ylim([-0.5, 1])
plt.show()

<Figure size 640x480 with 1 Axes>

In [28]:
N.zeros(9)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [29]:
N.fromfunction(lambda k,i, j: k+i+j, (3,3,3), dtype=int)

array([[[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]],

       [[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]]])