In [1]:
import numpy as np
a = np.arange(4)
print(a)

[0 1 2 3]


In [2]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [4]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [5]:
a = np.array([20,30,40,50])
b = np.arange(4)
c= a - b
print(c)

[20 29 38 47]


In [6]:
b**2

array([0, 1, 4, 9])

In [7]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [8]:
a<35

array([ True,  True, False, False], dtype=bool)

In [11]:
b = a<30
print(b)

[ True False False False]


In [16]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
print(A * B,"\n\n")
print(A @ B)

[[2 0]
 [0 4]] 


[[5 4]
 [3 4]]


In [18]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
print( a)

b += a
print(b)
#a += b


[[3 3 3]
 [3 3 3]]
[[ 3.02659328  3.09876642  3.57644578]
 [ 3.08230453  3.62329175  3.2725063 ]]


In [37]:
a = np.random.rand(2,3)
print(a)
print(a.sum())
print(a.min())
print(a.max(),"\n\n")
print("333\n",a.sum(axis=0)) #suma kazdej kolumny
print(a.sum(axis=1)) #suma kazdej wiersza
print("\n\n",a.min(axis=0)) #minmum w kazdej kolimniwe
print("\n\n",a.min(axis=1)) #minmum w kazdym wierszu

[[ 0.05242199  0.94636883  0.60501831]
 [ 0.94545317  0.5437734   0.70806865]]
3.80110434984
0.0524219884046
0.946368834118 


333
 [ 0.99787516  1.49014224  1.31308695]
[ 1.60380913  2.19729522]


 [ 0.05242199  0.5437734   0.60501831]


 [ 0.05242199  0.5437734 ]


In [38]:
b = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [39]:
print(b.cumsum(axis=1)) #kumulacja elementow w wierszu 0 0+a1 a1+a2+a3 itd

[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [42]:
print(np.exp(b)) #e ^b[i][j]

[[  1.00000000e+00   2.71828183e+00   7.38905610e+00   2.00855369e+01]
 [  5.45981500e+01   1.48413159e+02   4.03428793e+02   1.09663316e+03]
 [  2.98095799e+03   8.10308393e+03   2.20264658e+04   5.98741417e+04]]


In [46]:
A = np.array([[1,2],[0,0]])
B = np.array([[3,3],[2,1]])
C = np.add(A,B)
print(C)

[[4 5]
 [2 1]]


In [50]:
C = np.array([[True,True,False],[True,False,False]])
print(np.all(C,axis=0)) # spradzam czy w kazdej kolumnie jest prawda 
#mozna tez na liczbach

[ True False False]


In [53]:
print(np.any(C,axis=0)) #czy choć jedna prawda w kolumnie
print(np.any(C,axis=1)) #czy choć jedna prawda w wierszu


[ True  True False]
[ True  True]


In [58]:
def my_func(a):
    return a.sum()/2 #funkcja zwracajaca siednia w tablicy
b = np.array([[8,1,7], [4,3,9], [5,2,6]])
print(np.apply_along_axis(my_func,0,b))# wykozysytje nasza funkcje do maciezy funkcja
# funkcja robi cos na tablicach wedlug kolumn rob wierszy z zwraca wynik
b = np.array([[8,1,7], [4,3,9], [5,2,6]])
print(np.apply_along_axis(my_func,1,b))
print(np.apply_along_axis(np.diag, -1, b))

[  8.5   3.   11. ]
[ 8.   8.   6.5]
[[[8 0 0]
  [0 1 0]
  [0 0 7]]

 [[4 0 0]
  [0 3 0]
  [0 0 9]]

 [[5 0 0]
  [0 2 0]
  [0 0 6]]]


In [62]:
a = np.arange(6).reshape(2,3)
print(a)
print(np.argmax(a)) #zwraca maksymalny argument[index] do kad mozna iterowac
print(np.argmax(a,axis=0)) #jaki maksyam;bny index w kolumnie
#argmin( ) podonnie ale w druga strone

[[0 1 2]
 [3 4 5]]
5
[1 1 1]


In [72]:
 x = np.array([[6, 5, 4],[1,2,9]])#-> x[2],x[1],x[0]
print(np.argsort(x)) # zwraca indexz z jakieog miesjca przsysza cyfra
print(np.argsort(x,axis=0))

[[2 1 0]
 [0 1 2]]
[[1 1 0]
 [0 0 1]]


In [77]:
data =list(range(1,5))
print(data)
print(np.average(data))#srednia wazona


[1, 2, 3, 4]
2.5


In [83]:
data = np.arange(6).reshape((3,2))
print(data)
print(np.average(data,axis=1,weights=[1/4,3/4])) #wiersze*wagi /wagi

[[0 1]
 [2 3]
 [4 5]]
[ 0.75  2.75  4.75]
