In [2]:
import numpy as np
a = np.arange(6)**4
print(a)


[  0   1  16  81 256 625]


In [3]:
print(a[ : :-1])

[625 256  81  16   1   0]


In [6]:
# funkcja wywolujaca po indeksach

b = np.fromfunction(lambda i, j: i + j,(2,3))
print(b)

[[ 0.  1.  2.]
 [ 1.  2.  3.]]


In [20]:
b = np.fromfunction(lambda i ,j: i+j,(5,4),dtype=int)
print(b)
print(b[ : :-1 ,1]) # kolumna 2 od konca

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
[5 4 3 2 1]


In [21]:
b[2,3]

5

In [22]:
b[1 : 3, :]

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [23]:
b[-1]

array([4, 5, 6, 7])

In [24]:
for element in b.flat:
     print(element) #to wypisze po kolej jedno pod drugim

0
1
2
3
1
2
3
4
2
3
4
5
3
4
5
6
4
5
6
7


In [25]:
for element in b:
     print(element)

[0 1 2 3]
[1 2 3 4]
[2 3 4 5]
[3 4 5 6]
[4 5 6 7]


In [26]:
y = np.arange(35).reshape(5,7)
print(y)
print(y[1:5:2,::3])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
[[ 7 10 13]
 [21 24 27]]


In [28]:
print(y[ np.array([0,2,4,1]) , np.array([1,2,3,3]) ] ) # to daje x[0][1] x[2][2]itd

[ 1 16 31 10]


In [35]:
#ndeumerate zwraca numery indexów
a = np.array([[1, 2],[3, 4]])
for index,x in np.ndenumerate(a):
    print(index)
    print("dff",x)

<built-in method index of tuple object at 0x7f67cc08bf48>
dff 1
<built-in method index of tuple object at 0x7f67cc096f48>
dff 2
<built-in method index of tuple object at 0x7f67cc0cc588>
dff 3
<built-in method index of tuple object at 0x7f67cc093a48>
dff 4
