In [2]:
import numpy as np
a = np.arange(6)**4
print(a)


[  0   1  16  81 256 625]


In [3]:
print(a[ : :-1])

[625 256  81  16   1   0]


In [6]:
# funkcja wywolujaca po indeksach

b = np.fromfunction(lambda i, j: i + j,(2,3))
print(b)

[[ 0.  1.  2.]
 [ 1.  2.  3.]]


In [20]:
b = np.fromfunction(lambda i ,j: i+j,(5,4),dtype=int)
print(b)
print(b[ : :-1 ,1]) # kolumna 2 od konca

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
[5 4 3 2 1]


In [21]:
b[2,3]

5

In [22]:
b[1 : 3, :]

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [23]:
b[-1]

array([4, 5, 6, 7])

In [24]:
for element in b.flat:
     print(element) #to wypisze po kolej jedno pod drugim

0
1
2
3
1
2
3
4
2
3
4
5
3
4
5
6
4
5
6
7


In [25]:
for element in b:
     print(element)

[0 1 2 3]
[1 2 3 4]
[2 3 4 5]
[3 4 5 6]
[4 5 6 7]


In [26]:
y = np.arange(35).reshape(5,7)
print(y)
print(y[1:5:2,::3])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
[[ 7 10 13]
 [21 24 27]]


In [28]:
print(y[ np.array([0,2,4,1]) , np.array([1,2,3,3]) ] ) # to daje x[0][1] x[2][2]itd

[ 1 16 31 10]


In [35]:
#ndeumerate zwraca numery indexów
a = np.array([[1, 2],[3, 4]])
for index,x in np.ndenumerate(a):
    print(index)
    print("dff",x)

<built-in method index of tuple object at 0x7f67cc08bf48>
dff 1
<built-in method index of tuple object at 0x7f67cc096f48>
dff 2
<built-in method index of tuple object at 0x7f67cc0cc588>
dff 3
<built-in method index of tuple object at 0x7f67cc093a48>
dff 4


In [37]:
a = np.floor(5*np.random.random((3,4)))
print(a)
print(a.shape)

[[ 0.  3.  2.  2.]
 [ 3.  4.  3.  4.]
 [ 0.  4.  1.  1.]]
(3, 4)


In [43]:
#splaszca do jednego wymiaru revel
a = a.ravel()
print(a)
a = a.reshape(2,6) #ustawia nam wymiar tabeli ale tak by elementy sie zgadzaly 
print(a)
print(a.reshape(4,3)) # reshape(4,-1) wtredy drugi wymiar sam wylicza

[ 0.  3.  2.  2.  3.  4.  3.  4.  0.  4.  1.  1.]
[[ 0.  3.  2.  2.  3.  4.]
 [ 3.  4.  0.  4.  1.  1.]]
[[ 0.  3.  2.]
 [ 2.  3.  4.]
 [ 3.  4.  0.]
 [ 4.  1.  1.]]


In [50]:
a = np.array([[1,2],[4,5]])
print(a)
b = np.array([[3,7],[9,0]])
print(b)
print()
#skejaj mi dwi tablice albo jenda pod drug albo jedna obok drugiej
print(np.vstack((a,b)))
print()
print(np.hstack((a,b)))

[[1 2]
 [4 5]]
[[3 7]
 [9 0]]

[[1 2]
 [4 5]
 [3 7]
 [9 0]]

[[1 2 3 7]
 [4 5 9 0]]


In [52]:
#inne tworzenei tablicy jecngo zasiegu
print(np.r_[1:6,9,8])

[1 2 3 4 5 9 8]


In [61]:
#hsplit dzieli nam macierz
a = np.random.random((5,6))
print(np.hsplit(a,(3))) #biore do 3 tabele

[array([[ 0.38242397,  0.27075635],
       [ 0.44458985,  0.9422809 ],
       [ 0.75027266,  0.681678  ],
       [ 0.11093595,  0.99611698],
       [ 0.30488231,  0.52985581]]), array([[ 0.20338833,  0.13428402],
       [ 0.27299328,  0.6637692 ],
       [ 0.95299166,  0.77255537],
       [ 0.95534097,  0.64742635],
       [ 0.95006071,  0.91225438]]), array([[ 0.85462003,  0.50295943],
       [ 0.04069772,  0.58923648],
       [ 0.2145043 ,  0.5820572 ],
       [ 0.94139466,  0.63746496],
       [ 0.06436163,  0.27352454]])]


In [62]:
print(np.identity(4))
print()
print(np.eye(4)) #to zwraca maciez diagonalan 

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
